<?php
// config.php - Production config loader for PIXMORA AI
// This file loads sensitive config from config.local.php (created by installer).
// If config.local.php is not present, falls back to safe defaults (read-only) and minimal dev settings.

declare(strict_types=1);

// Prevent direct execution showing errors
error_reporting(E_ALL & ~E_DEPRECATED & ~E_STRICT);
if (getenv('APP_ENV') === 'production') {
    ini_set('display_errors', '0');
} else {
    ini_set('display_errors', '1');
}

// Base constants
define('APP_NAME', 'PIXMORA AI');
define('BASE_PATH', __DIR__);
define('ASSETS_PATH', BASE_PATH . '/assets');
define('UPLOAD_DIR', BASE_PATH . '/uploads');
define('DATA_DIR', BASE_PATH . '/data');

// Secure session defaults
ini_set('session.use_strict_mode', '1');
session_set_cookie_params([
    'lifetime' => 0,
    'path' => '/',
    'domain' => $_SERVER['HTTP_HOST'] ?? '',
    'secure' => (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off'),
    'httponly' => true,
    'samesite' => 'Lax'
]);
if (session_status() === PHP_SESSION_NONE) session_start();

// Load local config generated by installer
$localConfig = [];
if (file_exists(__DIR__ . '/config.local.php')) {
    $local = include __DIR__ . '/config.local.php';
    if (is_array($local)) $localConfig = $local;
}

// Provide a helper to read configuration
function pixmora_cfg() {
    global $localConfig;
    return $localConfig;
}

// Database connection factory (supports SQLite and MySQL)
function get_pdo() {
    static $pdo = null;
    if ($pdo) return $pdo;
    $cfg = pixmora_cfg();
    $db = $cfg['db'] ?? ['type' => 'sqlite', 'sqlite_path' => __DIR__ . '/data/database.sqlite'];

    if ($db['type'] === 'sqlite') {
        $path = $db['sqlite_path'] ?? __DIR__ . '/data/database.sqlite';
        if (!is_dir(dirname($path))) mkdir(dirname($path), 0755, true);
        $pdo = new PDO('sqlite:' . $path);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    } else {
        $host = $db['mysql_host'] ?? '127.0.0.1';
        $port = $db['mysql_port'] ?? '3306';
        $name = $db['mysql_db'] ?? '';
        $user = $db['mysql_user'] ?? '';
        $pass = $db['mysql_pass'] ?? '';
        $dsn = "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    }
    return $pdo;
}

// Basic security helpers
function h($v) { return htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
